/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarSelect: typeof import('./../src/layout/components/NavBar/AvatarSelect.vue')['default']
    Breadcrumb: typeof import('./../src/layout/components/NavBar/Breadcrumb.vue')['default']
    DarkBtn: typeof import('./../src/layout/components/NavBar/DarkBtn.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Fullscreen: typeof import('./../src/layout/components/NavBar/Fullscreen.vue')['default']
    Hamburger: typeof import('./../src/layout/components/NavBar/Hamburger.vue')['default']
    HeaderSearch: typeof import('./../src/layout/components/NavBar/HeaderSearch.vue')['default']
    Icons: typeof import('./../src/views/iconsView/components/Icons.vue')['default']
    Item: typeof import('./../src/layout/components/Sidebar/Item.vue')['default']
    LangSelect: typeof import('./../src/layout/components/NavBar/LangSelect.vue')['default']
    NavBar: typeof import('./../src/layout/components/NavBar/index.vue')['default']
    PanelGroup: typeof import('./../src/views/dashboard/components/PanelGroup.vue')['default']
    RightPanel: typeof import('./../src/layout/components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./../src/layout/components/TagsView/ScrollPane.vue')['default']
    SettingsItem: typeof import('./../src/layout/components/ViewsSettings/SettingsItem.vue')['default']
    Sidebar: typeof import('./../src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./../src/layout/components/Sidebar/SidebarItem.vue')['default']
    SizeSelect: typeof import('./../src/layout/components/NavBar/SizeSelect.vue')['default']
    TagsView: typeof import('./../src/layout/components/TagsView/index.vue')['default']
    ThemePicker: typeof import('./../src/components/ThemePicker/index.vue')['default']
    ViewsSettings: typeof import('./../src/layout/components/ViewsSettings/index.vue')['default']
  }
}
